# Use a minimal base image
[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.pip",
    "ffmpeg"
]

[phases.install]
cmds = [
    # Create minimal virtual environment
    "python -m venv --system-site-packages /app/venv",
    
    # Install only essential packages with no cache
    ". /app/venv/bin/activate && \
     cd backend && \
     pip install --no-cache-dir --upgrade pip && \
     pip install --no-cache-dir torch torchaudio --index-url https://download.pytorch.org/whl/cpu",
     
    # Install requirements with no cache and clean up
    ". /app/venv/bin/activate && \
     cd backend && \
     pip install --no-cache-dir -r requirements.txt && \
     find /app/venv -type d -name '__pycache__' -exec rm -r {} + && \
     find /app/venv -type d -name 'tests' -exec rm -r {} + && \
     find /app/venv -name '*.pyc' -delete"
]

[phases.build]
cmds = [
    "echo 'Cleaning up build dependencies...' && \
     rm -rf /tmp/* /var/tmp/* /root/.cache/* /var/cache/apt/*"
]

[variables]
# Enable HuggingFace offline mode to use cached models
TRANSFORMERS_OFFLINE = "1"
HF_DATASETS_OFFLINE = "1"

[start]
cmd = "cd backend && . /app/venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port $PORT"