[phases.setup]
nixPkgs = [
    'python311',
    'python311Packages.pip',
    'ffmpeg',
    'python311Packages.setuptools'
]

[phases.install]
cmds = [
    # Use Nix's Python packages instead of pip
    "cd backend && python -m pip install --user -r requirements.txt --break-system-packages"
]

[phases.build]
cmds = [
    "echo 'Skipping build phase'"
]

[start]
cmd = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"