[phases.setup]
nixPkgs = [
    'python311',
    'python311Packages.pip',
    'ffmpeg',
    'python311Packages.setuptools',
    'python311Packages.virtualenv'
]

[phases.install]
cmds = [
    # Create a virtual environment
    "python -m venv /app/venv",
    # Activate virtual environment and install requirements
    ". /app/venv/bin/activate && cd backend && pip install --upgrade pip && pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "echo 'Build phase completed'"
]

[start]
cmd = "cd backend && . /app/venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port $PORT"