services:
  - type: web
    name: voicera-backend
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
    startCommand: |
      cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
    plan: free
    region: oregon  # Choose the closest region to your users
